/** IPC 通道：业务语义 invoke + 已过滤的事件推送（连接生命周期由 main 自管，不暴露给 UI） */

export const CSOCKET_CHANNELS = {
  configure: 'csocket:configure',
  openProject: 'csocket:open-project',
  downloadPlcProject: 'csocket:download-plc-project',
  addDevicePlc: 'csocket:add-device-plc',
  deleteDevicePlc: 'csocket:delete-device-plc',
  modifyPlcParam: 'csocket:modify-plc-param',
  readPlcParamStatus: 'csocket:read-plc-param-status',
  handleDynamicOperation: 'csocket:handle-dynamic-operation',
  actionReady: 'csocket:action-ready',
  actionGo: 'csocket:action-go',
  actionStop: 'csocket:action-stop',


  // Motor
  configureAxisParamMotor: 'csocket:configure-axis-param-motor',
  enableMotor: 'csocket:enable-motor',
  resetAlarmMotor: 'csocket:reset-alarm-motor',
  clear731AlarmMotor: 'csocket:clear-731-alarm-motor',
  lightSlaveMotor: 'csocket:light-slave-motor',
  setPositionMotor: 'csocket:set-position-motor',
  jogMotor: 'csocket:jog-motor',
  moveAbsMotor: 'csocket:move-abs-motor',
  stopMotor: 'csocket:stop-motor',
  eStopMotor: 'csocket:e-stop-motor',
  torqueTestMotor: 'csocket:torque-test-motor',
  brakeTestMotor: 'csocket:brake-test-motor',
  commTestMotor: 'csocket:comm-test-motor',
  readAxisStateMotor: 'csocket:read-axis-state-motor',
  readAxisStatusMotor: 'csocket:read-axis-status-motor',
  configureAxisRunParamMotor: 'csocket:configure-axis-run-param-motor',
  readAxisRunParamMotor: 'csocket:read-axis-run-param-motor',

  // Model
  addModelWithDefaultValues: 'csocket:add-model-with-default-values',
  modifyModelType: 'csocket:modify-model-type',
  scanAllMaster: 'csocket:scan-all-master',
  coupleModel: 'csocket:couple-model',
  enableModel: 'csocket:enable-model',
  resetModel: 'csocket:reset-model',
  jogModel: 'csocket:jog-model',
  moveTargetModel: 'csocket:move-target-model',
  stopModel: 'csocket:stop-model',
  eStopModel: 'csocket:e-stop-model',
  configureModelParamModel: 'csocket:configure-model-param-model',
  configureRailBindingModel: 'csocket:configure-rail-binding-model',
  readModelInfo: 'csocket:read-model-info',

  // PLC ops / config
  simulationSwitchPlc: 'csocket:simulation-switch-plc',
  allStopPlc: 'csocket:all-stop-plc',
  busResetPlc: 'csocket:bus-reset-plc',
  resetPlc: 'csocket:reset-plc',
  ruleStartPlc: 'csocket:rule-start-plc',
  ruleDeletePlc: 'csocket:rule-delete-plc',
  addMotorPlc: 'csocket:add-axis-plc',
  syncMotorPlc: 'csocket:sync-motor-plc',
  deleteMotorPlc: 'csocket:delete-axis-plc',
  addModelPlc: 'csocket:add-model-plc',
  deleteModelPlc: 'csocket:delete-model-plc',
  downloadPlcInfoPlc: 'csocket:download-plc-info-plc',
  clearConfigPlc: 'csocket:clear-config-plc',
  disconnectMotionConfigPlc: 'csocket:disconnect-motion-config-plc',

  // PLC 读取 / 状态查询
  projectVerifyPlc: 'csocket:project-verify-plc',
  scanMasterPlc: 'csocket:scan-master-plc',
  readSlaveDevicesPlc: 'csocket:read-slave-devices-plc',
  slaveCommErrorPlc: 'csocket:slave-comm-error-plc',
  readRuleListPlc: 'csocket:read-rule-list-plc',
  autoListReadPlc: 'csocket:auto-list-read-plc',

  // C++ 主动发送事件通道
  // connectStatus: 'csocket:event:connect-status',
  // deviceStatus: 'csocket:event:device-status',
  // telemetry: 'csocket:event:telemetry',
  // alarm: 'csocket:event:alarm',
  // log: 'csocket:event:log',
  getMasterStatusSnapshot: 'csocket:get-master-status-snapshot',
  readMasterStatusPolling: 'csocket:event:read-master-status-polling',
  readModelInfoPolling: 'csocket:event:read-model-info-polling',
  readAxisInfoPolling: 'csocket:event:read-axis-info-polling',
  verifyProject: 'csocket:event:verify-project',
  clockSync: 'csocket:event:clock-sync',
} as const
